### ISSUE TITLE
Blender 2.93 error

### ISSUE THREAD

**Issue by rayluc3d** [Suemura/blender_luts_importer#5]
Hi there! 

I get this error trying to use the addon in Blender 2.93. It errors out after hitting the apply LUT button in the image editor:

Python: Traceback (most recent call last):
  File "C:\Users\raymo\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender_luts_importer-master\apply_lut_image.py", line 85, in execute
    self.apply_lut(context, temp_image, temp_pass)
  File "C:\Users\raymo\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender_luts_importer-master\apply_lut_image.py", line 57, in apply_lut
    for ver in os.listdir(path_roaming):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\raymo\\AppData\\Roaming\\Python'

location: <unknown location>:-1

**Comment by rayluc3d** [comment]
Also this error if i try to change the Select image dropdown to Viewer node and apply LUT:

Python: Traceback (most recent call last):
  File "C:\Users\raymo\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender_luts_importer-master\apply_lut_image.py", line 83, in execute
    self.copy_current_image(context, temp_image)
  File "C:\Users\raymo\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender_luts_importer-master\apply_lut_image.py", line 13, in copy_current_image
    shutil.copyfile(original_path, temp_image)
  File "C:\Program Files\Blender Foundation\blender-2.93.0-beta+blender-v293-release.8dd43ac23ebe-windows.amd64-release\2.93\python\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'C:\\Program Files\\Blender Foundation\\blender-2.93.0-beta+blender-v293-release.8dd43ac23ebe-windows.amd64-release'

location: <unknown location>:-1
